# Copyright (c) 2023-2024 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
# yaml-language-server: $schema=../../../../plugins/plugin_utils/schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  cv_pathfinder_regions:
    documentation_options:
      table: wan-cv-pathfinder-regions
    description: Define the CV Pathfinder hierarchy.
    type: list
    primary_key: name
    items:
      type: dict
      $ref: "eos_cli_config_gen#/keys/router_adaptive_virtual_topology/keys/region"
      keys:
        name:
          type: str
          min_length: 1
          max_length: 128
        description:
          type: str
        id:
          type: int
          description: |-
            The region ID must be unique for the whole WAN deployment.
        sites:
          type: list
          description: |-
            All sites are placed in a default zone "<region_name>-ZONE" with ID 1.
          primary_key: name
          items:
            type: dict
            $ref: "eos_cli_config_gen#/keys/router_adaptive_virtual_topology/keys/site"
            keys:
              name:
                type: str
                description: |-
                  The site name.
                min_length: 1
                max_length: 128
              description:
                type: str
              id:
                type: int
                description: |-
                  The site ID must be unique within a zone.
                  Given that all the sites are placed in a zone named after the region, the site ID must be unique within a region.
              location:
                type: str
                description: Location as a string is resolved on Cloudvision.
              site_contact:
                type: str
              site_after_hours_contact:
                type: str
        # Model for zones when required
        #zones:
        #  type: list
        #  primary_key: name
        #  items:
        #    type: dict
        #    $ref: "eos_cli_config_gen#/keys/router_adaptive_virtual_topology/keys/zone"
        #    keys:
        #      description:
        #        type: str
        #     id:
        #       type: int
        #       description: |-
        #         The zone ID must be unique per region.
        #      sites:
        #        type: list
        #        primary_key: name
        #        items:
        #          type: dict
        #          $ref: "eos_cli_config_gen#/keys/router_adaptive_virtual_topology/keys/site"
        #          keys:
        #            description:
        #              type: str
        #            location:
        #              type: str
        #              description: Will be interpreted
        #            site_contact:
        #              type: str
        #            site_after_hours_contact:
        #              type: str
