---
- name: Configure and Debug LACP/MLAG for VyOS Firewalls
  hosts: localhost
  gather_facts: false
  vars:
    allowed_vlans: "110,111"
    vyos01_portchannel: 7
    vyos02_portchannel: 8

  tasks:
    - name: Configure LACP for VyOS01 on DC1 Leaf Pair 1
      delegate_to: "{{ item }}"
      arista.eos.eos_config:
        lines:
          - "vlan {{ allowed_vlans.split(',') | join(',') }}"
          - "interface Port-Channel{{ vyos01_portchannel }}"
          - "  description VyOS01_LACP"
          - "  switchport mode trunk"
          - "  switchport trunk allowed vlan {{ allowed_vlans }}"
          - "  mlag {{ vyos01_portchannel }}"
          - "  no shutdown"
          - "interface Ethernet7"
          - "  description VyOS01_{{ item.upper() }}"
          - "  channel-group {{ vyos01_portchannel }} mode active"
          - "  no shutdown"
      loop:
        - DC1_LEAF1A
        - DC1_LEAF1B

    - name: Configure LACP for VyOS02 on DC1 Leaf Pair 2
      delegate_to: "{{ item }}"
      arista.eos.eos_config:
        lines:
          - "vlan {{ allowed_vlans.split(',') | join(',') }}"
          - "interface Port-Channel{{ vyos02_portchannel }}"
          - "  description VyOS02_LACP"
          - "  switchport mode trunk"
          - "  switchport trunk allowed vlan {{ allowed_vlans }}"
          - "  mlag {{ vyos02_portchannel }}"
          - "  no shutdown"
          - "interface Ethernet7"
          - "  description VyOS02_{{ item.upper() }}"
          - "  channel-group {{ vyos02_portchannel }} mode active"
          - "  no shutdown"
      loop:
        - DC1_LEAF2A
        - DC1_LEAF2B

    - name: Save Arista EOS configurations
      delegate_to: "{{ item }}"
      arista.eos.eos_config:
        save_when: always
      loop:
        - DC1_LEAF1A
        - DC1_LEAF1B
        - DC1_LEAF2A
        - DC1_LEAF2B

    - name: Check MLAG status on Arista switches
      delegate_to: "{{ item }}"
      arista.eos.eos_command:
        commands:
          - show mlag
          - show port-channel dense
          - show interfaces Ethernet7 status
      register: mlag_status
      ignore_errors: true
      loop:
        - DC1_LEAF1A
        - DC1_LEAF1B
        - DC1_LEAF2A
        - DC1_LEAF2B

    - name: Display MLAG Status
      debug:
        msg: "MLAG Status for {{ item.item }}: {{ item.stdout }}"
      loop: "{{ mlag_status.results }}"
      when: mlag_status.results is defined

    - name: Debug DC1_LEAF1B Configuration
      block:
        - name: Test basic connectivity to DC1_LEAF1B
          delegate_to: DC1_LEAF1B
          arista.eos.eos_command:
            commands:
              - show version | include Hostname
              - show version | include Software
          register: leaf1b_test
          ignore_errors: true

        - name: Display DC1_LEAF1B test results
          debug:
            var: leaf1b_test

        - name: Check current interface configuration on DC1_LEAF1B
          delegate_to: DC1_LEAF1B
          arista.eos.eos_command:
            commands:
              - show interfaces Ethernet7 | include Description
              - show interfaces Ethernet7 status
          register: leaf1b_current
          ignore_errors: true

        - name: Display current config
          debug:
            var: leaf1b_current

        - name: Force configure DC1_LEAF1B with simple test
          delegate_to: DC1_LEAF1B
          arista.eos.eos_config:
            lines:
              - "interface Ethernet7"
              - "  description TEST_LEAF1B_CONFIG"
              - "  no shutdown"
            save_when: always
          register: leaf1b_config
          ignore_errors: true

        - name: Display configuration result
          debug:
            var: leaf1b_config

        - name: Try full LACP configuration on DC1_LEAF1B
          delegate_to: DC1_LEAF1B
          arista.eos.eos_config:
            lines:
              - "vlan 110,111"
              - "interface Port-Channel7"
              - "  description VyOS01_LACP_LEAF1B"
              - "  switchport mode trunk"
              - "  switchport trunk allowed vlan 110,111"
              - "  mlag 7"
              - "  no shutdown"
              - "interface Ethernet7"
              - "  description VyOS01_DC1_LEAF1B"
              - "  channel-group 7 mode active"
              - "  no shutdown"
            save_when: always
          register: leaf1b_full_config
          ignore_errors: true

        - name: Display full configuration result
          debug:
            var: leaf1b_full_config

        - name: Verify final configuration
          delegate_to: DC1_LEAF1B
          arista.eos.eos_command:
            commands:
              - show interfaces Ethernet7 | include Description
              - show interfaces Port-Channel7 | include Description
              - show port-channel dense
          register: leaf1b_verify
          ignore_errors: true

        - name: Display verification result
          debug:
            var: leaf1b_verify

        - name: Compare with DC1_LEAF1A for reference
          delegate_to: DC1_LEAF1A
          arista.eos.eos_command:
            commands:
              - show interfaces Ethernet7 | include Description
              - show interfaces Port-Channel7 | include Description
              - show port-channel dense
          register: leaf1a_compare
          ignore_errors: true

        - name: Display DC1_LEAF1A comparison
          debug:
            var: leaf1a_compare

    - name: Debug DC1_LEAF2B Configuration
      block:
        - name: Test basic connectivity to DC1_LEAF2B
          delegate_to: DC1_LEAF2B
          arista.eos.eos_command:
            commands:
              - show version | include Hostname
              - show version | include Software
          register: leaf2b_test
          ignore_errors: true

        - name: Display DC1_LEAF2B test results
          debug:
            var: leaf2b_test

        - name: Check current interface configuration on DC1_LEAF2B
          delegate_to: DC1_LEAF2B
          arista.eos.eos_command:
            commands:
              - show interfaces Ethernet7 | include Description
              - show interfaces Ethernet7 status
          register: leaf2b_current
          ignore_errors: true

        - name: Display current config
          debug:
            var: leaf2b_current

        - name: Force configure DC1_LEAF2B with simple test
          delegate_to: DC1_LEAF2B
          arista.eos.eos_config:
            lines:
              - "interface Ethernet7"
              - "  description TEST_LEAF2B_CONFIG"
              - "  no shutdown"
            save_when: always
          register: leaf2b_config
          ignore_errors: true

        - name: Display configuration result
          debug:
            var: leaf2b_config

        - name: Try full LACP configuration on DC1_LEAF2B
          delegate_to: DC1_LEAF2B
          arista.eos.eos_config:
            lines:
              - "vlan 110,111"
              - "interface Port-Channel8"
              - "  description VyOS02_LACP_LEAF2B"
              - "  switchport mode trunk"
              - "  switchport trunk allowed vlan 110,111"
              - "  mlag 8"
              - "  no shutdown"
              - "interface Ethernet7"
              - "  description VyOS02_DC1_LEAF2B"
              - "  channel-group 8 mode active"
              - "  no shutdown"
            save_when: always
          register: leaf2b_full_config
          ignore_errors: true

        - name: Display full configuration result
          debug:
            var: leaf2b_full_config

        - name: Verify final configuration
          delegate_to: DC1_LEAF2B
          arista.eos.eos_command:
            commands:
              - show interfaces Ethernet7 | include Description
              - show interfaces Port-Channel8 | include Description
              - show port-channel dense
          register: leaf2b_verify
          ignore_errors: true

        - name: Display verification result
          debug:
            var: leaf2b_verify

        - name: Compare with DC1_LEAF2A for reference
          delegate_to: DC1_LEAF2A
          arista.eos.eos_command:
            commands:
              - show interfaces Ethernet7 | include Description
              - show interfaces Port-Channel8 | include Description
              - show port-channel dense
          register: leaf2a_compare
          ignore_errors: true

        - name: Display DC1_LEAF2A comparison
          debug:
            var: leaf2a_compare

- name: Configure Comprehensive Syslog for All Events on Arista Devices
  hosts: DC1_FABRIC
  gather_facts: no
  vars:
    syslog_destination: 172.16.10.118
    syslog_port: 514

  tasks:
    - name: Configure comprehensive Syslog settings for all subsystems
      arista.eos.eos_config:
        lines:
          - logging vrf MGMT host {{ syslog_destination }}
          - logging format hostname fqdn
          - logging facility local7
          - logging vrf MGMT source-interface Management0
          - logging level all informational
          - logging buffered 32768 informational
          - logging trap informational
          - logging console errors
          - logging monitor errors
        save_when: changed

    - name: Configuration completed
      debug:
        msg:
          - "Device: {{ inventory_hostname }}"
          - "Syslog Host: {{ syslog_destination }} via MGMT VRF"
          - "Source Interface: Management0 in MGMT VRF"
          - "Syslog configured for SSH, interfaces, routing, MLAG, and all events"

- name: Configure SNMP and Syslog on Arista Devices (Conservative)
  hosts: DC1_FABRIC
  gather_facts: no
  vars:
    snmp_community: public
    trap_destination: 172.16.10.118

  tasks:
    - name: Configure basic SNMP settings
      arista.eos.eos_config:
        lines:
          - snmp-server community {{ snmp_community }} ro
          - snmp-server vrf MGMT
          - snmp-server contact Network Operations sebatianm@selector.ai
          - snmp-server location New York Data Center
          - snmp-server chassis-id {{ inventory_hostname }}
          - snmp-server host {{ trap_destination }} vrf MGMT version 2c {{ snmp_community }}
          - snmp-server enable traps
          - snmp-server enable traps snmp authentication
          - snmp-server enable traps snmp link-down
          - snmp-server enable traps snmp link-up
        save_when: changed