download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/arista-cvp-3.12.0.tar.gz
format_version: 1.0.0
name: cvp
namespace: arista
server: https://galaxy.ansible.com/api/
signatures: []
version: 3.12.0
version_url: /api/v3/plugin/ansible/content/published/collections/index/arista/cvp/versions/3.12.0/
