version: '3.8'

services:
  # Network Device Manager (default)
  network-manager:
    build: .
    ports:
      - "8501:8501"
    volumes:
      # Mount playbooks directory to allow easy adding/editing of playbooks
      - ./playbooks:/app/playbooks
      # Mount logs directory to persist logs
      - ./logs:/app/logs
      # Optional: Mount SSH keys if needed for remote hosts
      # - ~/.ssh:/root/.ssh:ro
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_ENABLE_CORS=false
      - STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION=false
      - ANSIBLE_HOST_KEY_CHECKING=False
    restart: unless-stopped
    command: ["streamlit", "run", "network_app.py", "--server.port=8501", "--server.address=0.0.0.0"]
    networks:
      - ansible-net

  # General Ansible Playbook Runner
  ansible-runner:
    build: .
    ports:
      - "8502:8501"
    volumes:
      - ./playbooks:/app/playbooks
      - ./logs:/app/logs
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_ENABLE_CORS=false
      - STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION=false
      - ANSIBLE_HOST_KEY_CHECKING=False
    restart: unless-stopped
    command: ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
    networks:
      - ansible-net
    profiles:
      - general

networks:
  ansible-net:
    driver: bridge 