hostname: connected_endpoints
is_deployed: true
service_routing_protocols_model: multi-agent
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
- name: MGMT
  ip_routing: false
management_api_http:
  enable_vrfs:
  - name: MGMT
  enable_https: true
link_tracking_groups:
- name: LT_GROUP1
  recovery_delay: 300
ip_igmp_snooping:
  globally_enabled: true
ethernet_interfaces:
- name: Ethernet4
  peer: OLD_SW-1/4
  peer_type: server
  description: PHYSICAL_PORT_DESCRIPTION
  shutdown: false
  type: switched
- name: Ethernet5
  peer: OLD_SW-1/5
  peer_type: server
  description: OLD_SW-1/5
  shutdown: false
  type: port-channel-member
  channel_group:
    id: 5
    mode: active
- name: Ethernet6
  peer: OLD_SW-1/5
  peer_type: server
  description: OLD_SW-1/5
  shutdown: false
  type: port-channel-member
  channel_group:
    id: 5
    mode: active
- name: Ethernet7
  peer: OLD_SW-1/6
  peer_type: server
  description: PHYSICAL_PORT_DESCRIPTION
  shutdown: false
  type: port-channel-member
  channel_group:
    id: 7
    mode: active
- name: Ethernet8
  peer: OLD_SW-1/6
  peer_type: server
  description: PHYSICAL_PORT_DESCRIPTION
  shutdown: false
  type: port-channel-member
  channel_group:
    id: 7
    mode: active
- name: Ethernet9
  peer: SERVER_WITH_PLAYVAR_DESCRIPTION
  peer_type: server
  description: test of var set under play vars
  shutdown: false
  type: switched
- name: Ethernet10
  peer: OLD_SW-1/7
  peer_type: server
  description: PHYSICAL_PORT_DESCRIPTION_1
  shutdown: false
  type: port-channel-member
  channel_group:
    id: 10
    mode: active
- name: Ethernet11
  peer: OLD_SW-1/7
  peer_type: server
  description: PHYSICAL_PORT_DESCRIPTION_2
  shutdown: false
  type: port-channel-member
  channel_group:
    id: 10
    mode: active
- name: Ethernet12
  peer: INDIVIDUAL_1
  peer_type: server
  description: INDIVIDUAL_1
  shutdown: false
  type: switched
  channel_group:
    id: 12
    mode: active
  mode: trunk
  vlans: 1,2,3,4,5,6,7,123,234
  native_vlan_tag: false
  native_vlan: 123
  spanning_tree_portfast: edge
  spanning_tree_bpdufilter: 'True'
  dot1x:
    unauthorized:
      access_vlan_membership_egress: true
      native_vlan_membership_egress: true
  poe:
    disabled: true
  ptp:
    announce:
      interval: 0
      timeout: 3
    delay_req: -3
    sync_message:
      interval: -3
    transport: ipv4
    enable: true
    role: master
  service_profile: MYQOS
  sflow:
    enable: false
- name: Ethernet13
  peer: INDIVIDUAL_1
  peer_type: server
  description: INDIVIDUAL_1
  shutdown: false
  type: switched
  channel_group:
    id: 12
    mode: active
  mode: trunk
  vlans: 1,2,3,4,5,6,7,123,234
  native_vlan_tag: false
  native_vlan: 123
  spanning_tree_portfast: edge
  spanning_tree_bpdufilter: 'True'
  dot1x:
    unauthorized:
      access_vlan_membership_egress: true
      native_vlan_membership_egress: true
  poe:
    disabled: true
  ptp:
    announce:
      interval: 0
      timeout: 3
    delay_req: -3
    sync_message:
      interval: -3
    transport: ipv4
    enable: true
    role: master
  service_profile: MYQOS
  sflow:
    enable: false
- name: Ethernet14
  peer: DOT1X_UNAUTHORIZED
  peer_type: server
  port_profile: INDIVIDUAL_TRUNK
  description: DOT1X_UNAUTHORIZED
  shutdown: false
  type: switched
  mode: trunk
  vlans: 1,2,3,4,5,6,7,123,234
  native_vlan_tag: false
  native_vlan: 123
  spanning_tree_portfast: edge
  spanning_tree_bpdufilter: 'True'
  dot1x:
    unauthorized:
      access_vlan_membership_egress: true
      native_vlan_membership_egress: true
  poe:
    disabled: true
  ptp:
    announce:
      interval: 0
      timeout: 3
    delay_req: -3
    sync_message:
      interval: -3
    transport: ipv4
    enable: true
    role: master
  service_profile: MYQOS
  sflow:
    enable: false
- name: Ethernet15
  peer: INDIVIDUAL_2_TRUNK_PHONE
  peer_type: server
  description: INDIVIDUAL_2_TRUNK_PHONE
  shutdown: false
  type: switched
  channel_group:
    id: 15
    mode: active
  mode: trunk phone
  native_vlan: 123
  phone:
    vlan: 321
  link_tracking_groups:
  - name: LT_GROUP1
    direction: downstream
- name: Ethernet16
  peer: INDIVIDUAL_2_TRUNK_PHONE
  peer_type: server
  description: INDIVIDUAL_2_TRUNK_PHONE
  shutdown: false
  type: switched
  channel_group:
    id: 15
    mode: active
  mode: trunk phone
  native_vlan: 123
  phone:
    vlan: 321
  link_tracking_groups:
  - name: LT_GROUP1
    direction: downstream
port_channel_interfaces:
- name: Port-Channel5
  description: OLD_SW-1/5_PORT_CHANNEL_DESCRIPTION
  type: switched
  shutdown: false
- name: Port-Channel7
  description: PHYSICAL_PORT_DESCRIPTION_PORT_CHANNEL_DESCRIPTION
  type: switched
  shutdown: false
- name: Port-Channel10
  description: OLD_SW-1/7_PORT_CHANNEL_DESCRIPTION
  type: switched
  shutdown: false
- name: Port-Channel12
  description: INDIVIDUAL_1_INDIVIDUAL_1
  type: switched
  shutdown: false
  lacp_fallback_mode: individual
  lacp_fallback_timeout: 90
- name: Port-Channel15
  description: INDIVIDUAL_2_TRUNK_PHONE
  type: switched
  shutdown: false
  lacp_fallback_mode: individual
  lacp_fallback_timeout: 90
metadata:
  platform: 720XP
