hostname: inband-mgmt-dualstack-ips
is_deployed: true
service_routing_protocols_model: multi-agent
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
- name: MGMT
  ip_routing: false
management_api_http:
  enable_vrfs:
  - name: MGMT
  enable_https: true
ethernet_interfaces:
- name: Ethernet1
  peer: inband-mgmt-parent-dualstack1
  peer_interface: Ethernet25
  peer_type: l3leaf
  description: INBAND-MGMT-PARENT-DUALSTACK1_Ethernet25
  shutdown: false
  type: port-channel-member
  channel_group:
    id: 1
    mode: active
- name: Ethernet2
  peer: inband-mgmt-parent-dualstack2
  peer_interface: Ethernet25
  peer_type: l3leaf
  description: INBAND-MGMT-PARENT-DUALSTACK2_Ethernet25
  shutdown: false
  type: port-channel-member
  channel_group:
    id: 1
    mode: active
port_channel_interfaces:
- name: Port-Channel1
  description: INBAND-MGMT-PARENTS-DUALSTACK_Po25
  type: switched
  shutdown: false
  mode: trunk
  vlans: '105'
vlans:
- id: 105
  name: INBAND_MGMT
  tenant: system
ip_igmp_snooping:
  globally_enabled: true
vlan_interfaces:
- name: Vlan105
  description: Inband Management
  shutdown: false
  mtu: 1500
  ip_address: 192.168.105.22/24
  ipv6_enable: true
  ipv6_address: 2a00:105::123/64
  type: inband_mgmt
static_routes:
- destination_address_prefix: 0.0.0.0/0
  gateway: 192.168.105.1
ipv6_static_routes:
- destination_address_prefix: ::/0
  gateway: 2a00:105::1
