hostname: new_network_services_bgp_vrf_config_true
is_deployed: true
router_bgp:
  as: '65000'
  router_id: 192.168.42.1
  bgp:
    default:
      ipv4_unicast: false
  maximum_paths:
    paths: 4
    ecmp: 4
  updates:
    wait_install: true
  peer_groups:
  - name: IPv4-UNDERLAY-PEERS
    type: ipv4
    maximum_routes: 12000
    send_community: all
  address_family_ipv4:
    peer_groups:
    - name: IPv4-UNDERLAY-PEERS
      activate: true
  redistribute_routes:
  - source_protocol: connected
  vrfs:
  - name: PROD
    router_id: 192.168.42.1
    redistribute_routes:
    - source_protocol: connected
    address_family_ipv4:
      neighbors:
      - ip_address: 123.1.1.10
        activate: true
      - ip_address: 123.1.1.11
        activate: true
        prefix_list_in: PL-TEST-IN-AF4
        prefix_list_out: PL-TEST-OUT-AF4
    neighbors:
    - ip_address: 123.1.1.10
      remote_as: '1234'
      password: oBztv71m2uhR7hh58/OCNA==
      description: External IPv4 BGP peer
      send_community: standard extended
      maximum_routes: 0
      default_originate:
        always: false
        route_map: RM-PROD-123.1.1.10-SET-NEXT-HOP-OUT
      update_source: Loopback123
      ebgp_multihop: 3
      route_map_in: RM-123-1-1-10-IN
      shutdown: true
      route_map_out: RM-PROD-123.1.1.10-SET-NEXT-HOP-OUT
      local_as: '123'
    - ip_address: 123.1.1.11
      remote_as: '65000.100'
      password: oBztv71m2uhR7hh58/OCNA==
      description: External IPv4 BGP peer
      send_community: standard extended
      maximum_routes: 0
      default_originate:
        always: false
      update_source: Loopback123
      ebgp_multihop: 3
      route_map_in: RM-123-1-1-11-IN
      route_map_out: RM-123-1-1-11-OUT
      local_as: '123'
      bfd: true
    - ip_address: fd5a:fe45:8831:06c5::a
      remote_as: '12345'
      send_community: all
      route_map_out: RM-PROD-fd5a:fe45:8831:06c5::a-SET-NEXT-HOP-OUT
    - ip_address: fd5a:fe45:8831:06c5::b
      remote_as: '12345'
    address_family_ipv6:
      neighbors:
      - ip_address: fd5a:fe45:8831:06c5::a
        activate: true
        prefix_list_in: PL-TEST-IN-AF6
        prefix_list_out: PL-TEST-OUT-AF6
      - ip_address: fd5a:fe45:8831:06c5::b
        activate: true
    updates:
      wait_install: true
service_routing_protocols_model: multi-agent
ip_routing: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
- name: MGMT
  ip_routing: false
- name: PROD
  tenant: TenantA
  ip_routing: true
management_api_http:
  enable_vrfs:
  - name: MGMT
  enable_https: true
loopback_interfaces:
- name: Loopback0
  description: Router_ID
  shutdown: false
  ip_address: 192.168.42.1/32
ip_igmp_snooping:
  globally_enabled: true
ip_virtual_router_mac_address: cafe:cafe:cafe
ethernet_interfaces:
- name: Ethernet7
  peer_type: l3_interface
  ip_address: 10.10.10.10/24
  mtu: 9000
  shutdown: false
  description: test
  type: routed
  vrf: PROD
route_maps:
- name: RM-PROD-123.1.1.10-SET-NEXT-HOP-OUT
  sequence_numbers:
  - sequence: 10
    type: permit
    set:
    - ip next-hop 123.1.1.1
- name: RM-PROD-fd5a:fe45:8831:06c5::a-SET-NEXT-HOP-OUT
  sequence_numbers:
  - sequence: 10
    type: permit
    set:
    - ipv6 next-hop fd5a:fe45:8831:06c5::1
metadata:
  platform: vEOS-LAB
