hostname: sflow-tests-l2-leaf1
is_deployed: true
static_routes:
- vrf: MGMT
  destination_address_prefix: 0.0.0.0/0
  gateway: 192.168.0.1
- destination_address_prefix: 0.0.0.0/0
  gateway: 10.254.254.1
service_routing_protocols_model: multi-agent
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
- name: MGMT
  ip_routing: false
management_interfaces:
- name: Management1
  description: oob_management
  shutdown: false
  vrf: MGMT
  ip_address: 192.168.0.201/24
  gateway: 192.168.0.1
  type: oob
management_api_http:
  enable_vrfs:
  - name: MGMT
  enable_https: true
ethernet_interfaces:
- name: Ethernet1
  peer: sflow-tests-leaf3
  peer_interface: Ethernet16
  peer_type: l3leaf
  description: SFLOW-TESTS-LEAF3_Ethernet16
  shutdown: false
  type: port-channel-member
  channel_group:
    id: 1
    mode: active
- name: Ethernet2
  peer: sflow-tests-leaf4
  peer_interface: Ethernet16
  peer_type: l3leaf
  description: SFLOW-TESTS-LEAF4_Ethernet16
  shutdown: false
  type: port-channel-member
  channel_group:
    id: 1
    mode: active
port_channel_interfaces:
- name: Port-Channel1
  description: SFLOW-TESTS-LEAF-MLAG_Po16
  type: switched
  shutdown: false
  mode: trunk
  sflow:
    enable: true
  vlans: 11,4092
vlans:
- id: 11
  name: VLAN11
  tenant: SFLOW
- id: 4092
  tenant: system
  name: INBAND_MGMT
ip_igmp_snooping:
  globally_enabled: true
vlan_interfaces:
- name: Vlan4092
  description: Inband Management
  shutdown: false
  mtu: 1500
  ip_address: 10.254.254.4/24
  type: inband_mgmt
sflow:
  run: true
  sample: 10
  destinations:
  - destination: 10.10.10.10
  - destination: 10.10.10.11
  source_interface: Vlan4092
  vrfs:
  - name: MGMT
    destinations:
    - destination: 10.10.10.12
    source_interface: Management1
metadata:
  platform: vEOS-lab
