# Copyright (c) 2023-2024 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
---
#########################################
##  Run eos_validate_state using ANTA  ##
#########################################

- name: Run eos_validate_state_runner leveraging ANTA
  arista.avd.eos_validate_state_runner:
    logging_level: "{{ logging_level | arista.avd.default('WARNING') }}"
    skipped_tests: "{{ skipped_tests | arista.avd.default([]) }}"
    save_catalog: "{{ save_catalog | arista.avd.default(false) }}"
    device_catalog_path: "{{ test_catalogs_dir }}/{{ inventory_hostname }}-catalog.yml"
    test_results_dir: "{{ test_results_dir }}"
    custom_anta_catalogs_dir: "{{ custom_anta_catalogs_dir }}"
    # cprofile_file: "anta-{{inventory_hostname}}.prof"
  register: anta_results
  check_mode: false
  tags: always

#######################################
##  Generate reports from ANTA tests ##
#######################################

- name: Create validation reports from ANTA tests
  arista.avd.eos_validate_state_reports:
    csv_report_path: "{{ eos_validate_state_csv_report_path }}"
    md_report_path: "{{ eos_validate_state_md_report_path }}"
    validation_report_csv: "{{ validation_report_csv }}"
    validation_report_md: "{{ validation_report_md }}"
    only_failed_tests: "{{ only_failed_tests }}"
    test_results_dir: "{{ test_results_dir }}"
    # cprofile_file: "eos_validate_state_reports.prof"
  delegate_to: localhost
  run_once: true
  check_mode: false
  when:
    - validation_report_csv | bool or validation_report_md | bool
  tags:
    - always
    - reports
