---
- name: EOS Interface Enable/Disable
  hosts: DC1_SPINES:DC1_LEAFS
  gather_facts: false
  
  vars:
    target_device: "{{ target_host | default('DC1_LEAF1A') }}"
    target_interface: "{{ interface_name | default('Ethernet1') }}"
    interface_action: "{{ action | default('disable') }}"  # enable or disable
    interface_description: "{{ description | default('') }}"
  
  tasks:
    - name: Skip if not target device
      meta: end_host
      when: inventory_hostname != target_device
    
    - name: Show current interface status
      arista.eos.eos_command:
        commands:
          - "show interfaces {{ target_interface }} status"
      register: current_status
    
    - name: Display current interface status
      debug:
        msg: |
          Current status of {{ target_interface }} on {{ inventory_hostname }}:
          {{ current_status.stdout[0] }}
    
    - name: Configure interface - Enable
      arista.eos.eos_interfaces:
        config:
          - name: "{{ target_interface }}"
            enabled: true
            description: "{{ interface_description if interface_description else 'Enabled via Streamlit App at ' + ansible_date_time.iso8601 }}"
        state: merged
      when: interface_action == 'enable'
      register: enable_result
    
    - name: Configure interface - Disable  
      arista.eos.eos_interfaces:
        config:
          - name: "{{ target_interface }}"
            enabled: false
            description: "{{ interface_description if interface_description else 'Disabled via Streamlit App at ' + ansible_date_time.iso8601 }}"
        state: merged
      when: interface_action == 'disable'
      register: disable_result
    
    - name: Wait for interface change to take effect
      pause:
        seconds: 2
    
    - name: Verify interface status after change
      arista.eos.eos_command:
        commands:
          - "show interfaces {{ target_interface }} status"
      register: new_status
    
    - name: Display new interface status
      debug:
        msg: |
          ========================================
          INTERFACE CHANGE RESULT
          ========================================
          Device: {{ inventory_hostname }}
          Interface: {{ target_interface }}
          Action: {{ interface_action | upper }}
          
          BEFORE:
          {{ current_status.stdout[0] }}
          
          AFTER:
          {{ new_status.stdout[0] }}
          
          Status: {{ 'SUCCESS' if (enable_result.changed or disable_result.changed) else 'NO CHANGE NEEDED' }}
    
    - name: Save interface change log
      copy:
        content: |
          ========================================
          INTERFACE CHANGE LOG
          ========================================
          Timestamp: {{ ansible_date_time.iso8601 }}
          Device: {{ inventory_hostname }}
          Interface: {{ target_interface }}
          Action: {{ interface_action | upper }}
          Changed: {{ enable_result.changed or disable_result.changed }}
          
          BEFORE:
          {{ current_status.stdout[0] }}
          
          AFTER:
          {{ new_status.stdout[0] }}
        dest: "/tmp/{{ inventory_hostname }}_{{ target_interface }}_change_log.txt"
        mode: '0644'
      delegate_to: localhost 