---
- name: Cleanup - Configuration deployment with CVP
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    cv_server: www.cv-staging.corp.arista.io
    cv_token: "{{ lookup('env', 'CVAAS_AAWG_CI') }}"
    cv_verify_certs: false
    cv_devices: [ci-s1-leaf1, ci-s1-leaf2, ci-s1-leaf3, ci-s1-leaf4, ci-s1-spine1, ci-s1-spine2 ]
    cv_skip_missing_devices: true
    eos_config_dir: "{{ playbook_dir }}/intended/configs/base_configs"
    structured_dir: "{{ playbook_dir }}/intended/structured_configs/base_configs"

  tasks:
    - name: Generate random string
      ansible.builtin.set_fact:
        r: "{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=4') }}"
      run_once: true

    - name: Set facts
      ansible.builtin.set_fact:
        cv_workspace_name: avd-cv-deploy-cleanup-{{ r }}
        cv_workspace_description: sample description
        cv_change_control_name: cc_cv_deploy-cleanup-{{ r }}
        cv_change_control_description: sample description
        cv_register_detailed_results: true
      run_once: true

    - name: Cleanup
      run_once: true
      delegate_to: localhost
      ansible.builtin.import_role:
        name: arista.avd.cv_deploy
      vars:
        cv_submit_workspace: true
        cv_submit_workspace_force: true
        cv_run_change_control: true
        cv_strict_tags: true
