# Enable vlan aware bundles
evpn_vlan_aware_bundles: false

type: l3leaf

l3leaf:
  defaults:
    # LOOPBACK AND VTEP MANAGEMENT
    loopback_ipv4_pool: 10.10.0.0/24
    vtep_loopback_ipv4_pool: 10.11.0.0/24
    vtep_loopback: Loopback1
    # Possibility to prevent configuration of Tenant VRFs and SVIs. This allows support for centralized routing.
    evpn_services_l2_only: false
  nodes:
    - name: evpn_vlan_bundle_svi_l2vlan
      id: 3
      bgp_as: 65101
      filter:
        tags: [fabric, ipmi, storageProd, sit]

tenants:
  - name: SIT
    vlan_aware_bundle_number_base: 300
    mac_vrf_vni_base: 20000
    l2vlans:
      - id: 10
        name: storage_prod
        tags: ['storageProd']
      - id: 20
        name: storage_prod
        tags: ['storageProd']
      - id: 90
        name: vlan90
        tags: ['ipmi']
        evpn_vlan_bundle: bundle3
      - id: 100
        name: vlan100
        tags: ['fabric']
        evpn_vlan_bundle: bundle3
    vrfs:
      - name: SIT_VRF
        vrf_vni: 789654
        svis:
          - id: 1008
            name: SVI_1
            enabled: true
            evpn_vlan_bundle: bundle3
            tags: ['sit']
          - id: 1009
            name: SVI_2
            enabled: true
            evpn_vlan_bundle: bundle3
            tags: ['sit']
          - id: 1010
            name: SVI_3
            enabled: true
            tags: ['sit']

evpn_vlan_bundles:
  - name: bundle3
    id: 3
    rt_override: 333
    rd_override: 1.1.1.1:333
