# Enable vlan aware bundles
evpn_vlan_aware_bundles: true

type: l3leaf

l3leaf:
  defaults:
    # LOOPBACK AND VTEP MANAGEMENT
    loopback_ipv4_pool: 10.10.0.0/24
    vtep_loopback_ipv4_pool: 10.11.0.0/24
    vtep_loopback: Loopback1
    # Possibility to prevent configuration of Tenant VRFs and SVIs. This allows support for centralized routing.
    evpn_services_l2_only: false
  nodes:
    - name: evpn_vlan_bundle
      id: 3
      bgp_as: 65101
      filter:
        tags: [fabric, ipmi, storageProd, sit]

tenants:
  - name: StorageProd
    vlan_aware_bundle_number_base: 100
    mac_vrf_vni_base: 10000
    l2vlans:
      - id: 10
        name: storage_prod
        tags: ['storageProd']
      - id: 20
        name: storage_prod
        tags: ['storageProd']
  - name: FABRIC
    vlan_aware_bundle_number_base: 200
    mac_vrf_vni_base: 10000
    l2vlans:
      - id: 50
        name: ipmi
        tags: ['ipmi']
        evpn_vlan_bundle: bundle1
      - id: 60
        name: ipmi
        tags: ['fabric']
        evpn_vlan_bundle: bundle1
      - id: 70
        name: vmotion
        tags: ['ipmi']
        evpn_vlan_bundle: bundle2
      - id: 80
        name: vstorage
        tags: ['fabric']
        evpn_vlan_bundle: bundle2
  - name: SIT
    vlan_aware_bundle_number_base: 300
    mac_vrf_vni_base: 20000
    l2vlans:
      - id: 90
        name: vlan90
        tags: ['ipmi']
        evpn_vlan_bundle: bundle3
      - id: 100
        name: vlan100
        tags: ['fabric']
        evpn_vlan_bundle: bundle3
    vrfs:
      - name: SIT_VRF
        vrf_vni: 789654
        svis:
          - id: 1008
            name: SVI_1
            enabled: true
            evpn_vlan_bundle: bundle3
            tags: ['sit']
          - id: 1009
            name: SVI_2
            enabled: true
            evpn_vlan_bundle: bundle3
            tags: ['sit']
          - id: 1010
            name: SVI_3
            enabled: true
            tags: ['sit']
      - name: SIT2
        vrf_vni: 654789
        svis:
          - id: 1011
            name: SVI_4
            enabled: true
            evpn_vlan_bundle: bundle3
            tags: ['sit']
          - id: 1012
            name: SVI_5
            enabled: true
            evpn_vlan_bundle: bundle3
            tags: ['sit']
          - id: 1013
            name: SVI_6
            enabled: true
            tags: ['sit']
      - name: SIT3
        vrf_vni: 654555
        svis:
          - id: 1014
            name: SVI_7
            enabled: true
            evpn_vlan_bundle: bundle4
            tags: ['sit']
          - id: 1015
            name: SVI_8
            enabled: true
            evpn_vlan_bundle: bundle4
            tags: ['sit']

evpn_vlan_bundles:
  - name: bundle1
    id: 1
    bgp:
      raw_eos_cli: |
        vlan add 1000
  - name: bundle2
    id: 2
    rt_override: 111
    rd_override: 1.1.1.1:222
  - name: bundle3
    id: 3
    rt_override: 333
    rd_override: 1.1.1.1:333
  - name: bundle4
    id: 4
    rt_override: 444
    rd_override: 1.1.1.1:444
