# Negative test to catch dangerous interval false for router bfd and make sure the
# error message makes sense to the user
router_bfd:
  session_snapshot_interval: 6
  session_snapshot_interval_dangerous: false

expected_error_message: "router_bfd.session_snapshot_interval_dangerous was set to False but we expected True!"
