loopback_ipv4_pool: 192.168.0.0/24

type: l2leaf
l2leaf:
  defaults:
  nodes:
    - name: connected-endpoints-wrong-profile-lacp-fallback

servers:
  # port-channel with lacp fallback individual and missing profile for lacp fallback
  - name: INDIVIDUAL_1
    adapters:
      - switches: [connected-endpoints-wrong-profile-lacp-fallback, connected-endpoints-wrong-profile-lacp-fallback]
        switch_ports: [Ethernet14, Ethernet15]
        port_channel:
          mode: "active"
          description: "INDIVIDUAL_1"
          lacp_fallback:
            mode: individual
            individual:
              profile: INDIVIDUAL_TRUNK

port_profiles:
  - profile: INDIVIDUAL_TRUNKS
    mode: trunk
    vlans: "1,2,3,4,5,6,7,123,234"
    native_vlan_tag: False
    native_vlan: 123

expected_error_message: "The 'profile' of every port-channel lacp fallback individual setting must be defined in the 'port_profiles'. First occurrence seen of a missing profile is 'INDIVIDUAL_TRUNK' for the connected endpoint with the name 'INDIVIDUAL_1'."
