---
fabric_name: fabric_p2p_vrfs

default_node_types:
  - node_type: not_underlay_router
    match_hostnames:
      - ".*underlay.*"

node_type_keys:
  - key: not_underlay_router
    type: not_underlay_router
    underlay_router: false
    uplink_type: p2p-vrfs

not_underlay_router:
  nodes:
    - name: invalid-uplink-type-p2p-vrfs-underlay-router-false

expected_error_message: "Unexpected failure during module execution: 'underlay_router' and 'network_services.l3' must be 'true' for the node_type_key when using 'p2p-vrfs' as 'uplink_type'."
