type: l2leaf
l2leaf:
  nodes:
    - name: sflow-settings-missing-mgmt-ip
      id: 1

sflow_settings:
  destinations:
    - destination: 10.10.10.10
      vrf: use_mgmt_interface_vrf

servers:
  - name: test
    adapters:
      - switches: [sflow-settings-missing-mgmt-ip]
        switch_ports: [Ethernet1]
        sflow: true

expected_error_message: >-
  Unable to configure sFlow source-interface with 'use_mgmt_interface_vrf' since 'mgmt_ip' or 'ipv6_mgmt_ip' are not set.
