---
all:
  children:
    EOS_DESIGNS_FACTS_FAILURES: # Add cases that fail during 'eos_designs_facts' phase.
      # Each case _must_ be in it's own 'fabric' group set as 'fabric_name' in the hostvars
      # Each case must be added to converge.yml as a separate play - otherwise the eos_designs_facts fabric_name check will fail.
      children:
        fabric_missing_mlag_peer:
          hosts:
            missing-mlag-peer:
        fabric_ip_addressing_mlag_odd_id:
          hosts:
            mlag_odd_id_oddodd1:
            mlag_odd_id_oddodd2:
        fabric_ip_addressing_mlag_same_subnet:
          hosts:
            mlag_same_subnet_1:
            mlag_same_subnet_2:
        fabric_invalid_schema:
          hosts:
            invalid-schema:
        fabric_invalid_schema_connected_endpoints:
          hosts:
            invalid-schema-connected-endpoints:
        fabric_removed_schema_connected_endpoints:
          hosts:
            removed-schema-connected-endpoints:
        fabric_invalid_uplink_port_channel_id_1:
          hosts:
            invalid-uplink-port-channel-id-l3leaf-1:
            invalid-uplink-port-channel-id-l3leaf-2:
            invalid-uplink-port-channel-id-l2leaf-1:
            invalid-uplink-port-channel-id-l2leaf-2:
        fabric_invalid_uplink_port_channel_id_2:
        # Notice the same hosts since all vars are given in group var
          hosts:
            invalid-uplink-port-channel-id-l3leaf-1:
            invalid-uplink-port-channel-id-l3leaf-2:
            invalid-uplink-port-channel-id-l2leaf-1:
            invalid-uplink-port-channel-id-l2leaf-2:
        fabric_invalid_uplink_port_channel_id_3:
        # Notice the same hosts since all vars are given in group var
          hosts:
            invalid-uplink-port-channel-id-l3leaf-1:
            invalid-uplink-port-channel-id-l3leaf-2:
            invalid-uplink-port-channel-id-l2leaf-1:
            invalid-uplink-port-channel-id-l2leaf-2:
        fabric_wan_role_overlay_routing_protocol:
          hosts:
            invalid-wan-role-overlay-routing-protocol:
        fabric_p2p_vrfs:
          hosts:
            invalid-uplink-type-p2p-vrfs-underlay-router-false:
        fabric_downlink_pools_missing:
          hosts:
            downlink-pools-missing-spine:
            downlink-pools-missing-l3leaf:
        fabric_downlink_pools_duplicate:
          hosts:
            downlink-pools-duplicate-spine:
            downlink-pools-duplicate-l3leaf:
    EOS_DESIGNS_FAILURES: # Add cases that fail during 'eos_designs_structured_config' phase
      children:
        EOS_DESIGNS_FAILURES_INCLUDED:
          hosts:
            failure-port-channel:
            connected-endpoints-mismatched-descriptions:
            connected-endpoints-missing-profile-lacp-fallback:
            connected-endpoints-wrong-profile-lacp-fallback:
            connected-endpoints-phone-vlan-mode:
            connected-endpoints-phone-vlan-vlans:
            connected-endpoints-monitor-sessions-mismatch-direction:
            duplicate-vlans-l2vlans:
            duplicate-vlans-svi-id:
            duplicate-vrfs-duplicate-svi-name-conflict:
            duplicate-vrfs-id-conflict:
            duplicate-vrfs-vni-conflict:
            duplicate-vrfs-tenant-igmp-snooping-conflict:
            duplicate-interface-l3-edge:
            duplicate-l3-interfaces-network-services:
            duplicate-interfaces-point-to-point-services-1:
            duplicate-interfaces-point-to-point-services-2:
            duplicate-interfaces-point-to-point-services-3:
            duplicate-interfaces-point-to-point-services-4:
            duplicate-interfaces-connected-endpoints:
            duplicate-interfaces-core-interfaces:
            duplicate-interfaces-core-interfaces-with-port-channel:
            duplicate-vni-vxlan-interface:
            duplicate-vni-l3-interfaces-in-vxlan-interface:
            duplicate-vni-l2vlans-vxlan-interface:
            duplicate-interfaces-underlay:
            duplicate-ip-address-uplink-switch-router-bgp:
            duplicate-tunnel-interface-internet-exit:
            failure-missing-evpn-vlan-bundle:
            failure-missing-evpn-vlan-bundle_svi:
            failure-missing-evpn-multicast-l3-with-pim:
            failure-missing-evpn-multicast-peg-rps:
            failure-duplicate-evpn-vlan-bundle-name:
            failure-no-local-path-group-in-default-policy:
            ipv4-acl-in-missing-on-wan-interface:
            ipv4-acls:
            missing-avt-id-cv-pathfinder:
            missing-data-plane_cpu-allocation-max:
            ntp-settings-server-vrf-missing-mgmt-ip:
            ntp-settings-server-vrf-missing-inband-mgmt-interface:
            source-interfaces-domain-lookup-duplicate-vrf:
            source-interfaces-domain-lookup-missing-inband-mgmt-interface:
            source-interfaces-domain-lookup-missing-mgmt-ip:
            source-interfaces-http-client-duplicate-vrf:
            source-interfaces-http-client-missing-inband-mgmt-interface:
            source-interfaces-http-client-missing-mgmt-ip:
            source-interfaces-radius-duplicate-vrf:
            source-interfaces-radius-missing-inband-mgmt-interface:
            source-interfaces-radius-missing-mgmt-ip:
            source-interfaces-ssh-client-duplicate-vrf:
            source-interfaces-ssh-client-missing-inband-mgmt-interface:
            source-interfaces-ssh-client-missing-mgmt-ip:
            source-interfaces-tacacs-duplicate-vrf:
            source-interfaces-tacacs-missing-inband-mgmt-interface:
            source-interfaces-tacacs-missing-mgmt-ip:
            ul-filter-evpn-default-vrf-services:
            sflow-settings-missing-inband-mgmt-interface:
            sflow-settings-missing-mgmt-ip:

          children:
            duplicate-vlans-mlag:
              hosts:
                duplicate-vlans-mlag-a:
                duplicate-vlans-mlag-b:

        EOS_DESIGNS_FAILURES_EXCLUDED:
          # These hosts are included in the vars and facts, but will not be included in the structured config run,
          # since they are not present to trigger a failure on a different device.
          children:
            duplicate-ip-address-router-bgp:
              hosts:
                duplicate-ip-address-1:
                duplicate-ip-address-2:
