# Copyright (c) 2023-2024 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
# yaml-language-server: $schema=../../../../plugins/plugin_utils/schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  match_list_input:
    type: dict
    display_name: Match Lists
    keys:
      prefix_ipv4:
        type: list
        primary_key: name
        items:
          type: dict
          keys:
            name:
              type: str
              description: Prefix-List Name.
            prefixes:
              type: list
              required: true
              min_length: 1
              description: List of IPv4 prefixes (with the subnet mask e.g. 192.0.2.0/24).
              items:
                type: str
      prefix_ipv6:
        type: list
        primary_key: name
        items:
          type: dict
          keys:
            name:
              type: str
              description: Prefix-List Name.
            prefixes:
              type: list
              required: true
              min_length: 1
              description: List of IPv6 prefixes (with the subnet mask e.g. 2001:db8:abcd:0013::/64).
              items:
                type: str
      string:
        type: list
        primary_key: name
        convert_types:
          - dict
        items:
          type: dict
          keys:
            name:
              type: str
              description: Match-list Name.
            sequence_numbers:
              type: list
              required: true
              primary_key: sequence
              convert_types:
                - dict
              items:
                type: dict
                keys:
                  sequence:
                    type: int
                    description: Sequence ID.
                    convert_types:
                      - str
                  match_regex:
                    type: str
                    required: true
                    description: Regular Expression.
