# Enable vlan aware bundles
evpn_vlan_aware_bundles: true

type: l3leaf

l3leaf:
  defaults:
    # LOOPBACK AND VTEP MANAGEMENT
    loopback_ipv4_pool: 10.10.0.0/24
    vtep_loopback_ipv4_pool: 10.11.0.0/24
    vtep_loopback: Loopback1
    # Possibility to prevent configuration of Tenant VRFs and SVIs. This allows support for centralized routing.
    evpn_services_l2_only: false
  nodes:
    - name: failure-missing-evpn-vlan-bundle_svi
      id: 3
      bgp_as: 65101
      filter:
        tags: [sit]

tenants:
  - name: SIT
    mac_vrf_vni_base: 20000
    vrfs:
      - name: SIT_VRF
        vrf_vni: 654789
        svis:
          - id: 1008
            name: SVI_1
            enabled: true
            evpn_vlan_bundle: bundle1
            tags: ['sit']
          - id: 1009
            name: SVI_2
            enabled: true
            evpn_vlan_bundle: bundle2
            tags: ['sit']

evpn_vlan_bundles:
  - name: bundle1
    id: 1

expected_error_message: >-
  The 'evpn_vlan_bundle' of the svis/l2vlans must be defined in the common 'evpn_vlan_bundles' setting. First occurrence seen for svi/l2vlan 1009 in Tenant 'SIT' and evpn_vlan_bundle 'bundle2'.
