---
type: spine

spine:
  nodes:
    - bgp_as: 65000
      name: ipv4-acls
      id: 1
      loopback_ipv4_pool: 192.168.0.0/24
      l3_interfaces:
        - name: Ethernet1
          ip_address: 172.16.0.2/30
          ipv4_acl_in: TEST-IPV4-ACL-WITH-IP-FIELDS-IN
          ipv4_acl_out: TEST-IPV4-ACL-WITH-IP-FIELDS-OUT
          # peer_ip: 172.16.0.1/30 Testing not filling in the peer_ip will raise an error.


ipv4_acls:
# ip_access_lists:
  - name: TEST-IPV4-ACL-WITH-IP-FIELDS-IN
    entries:
      - sequence: 15
        action: deny
        protocol: ip
        source: any
        destination: interface_ip
      - action: permit
        protocol: ip
        source: peer_ip
        destination: interface_ip

expected_error_message: >-
  Unable to perform substitution of the value 'peer_ip' defined under 'ipv4_acls[name=TEST-IPV4-ACL-WITH-IP-FIELDS-IN].entries[1].source',
  since no substitution value was found for interface 'Ethernet1'. Make sure to set the appropriate fields on the interface.
