hostname: inband-mgmt-ipv6-only
is_deployed: true
service_routing_protocols_model: multi-agent
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
- name: MGMT
  ip_routing: false
management_api_http:
  enable_vrfs:
  - name: MGMT
  enable_https: true
ethernet_interfaces:
- name: Ethernet1
  peer: inband-mgmt-parent-ipv6-1
  peer_interface: Ethernet26
  peer_type: l3leaf
  description: INBAND-MGMT-PARENT-IPV6-1_Ethernet26
  shutdown: false
  type: port-channel-member
  channel_group:
    id: 1
    mode: active
- name: Ethernet2
  peer: inband-mgmt-parent-ipv6-2
  peer_interface: Ethernet26
  peer_type: l3leaf
  description: INBAND-MGMT-PARENT-IPV6-2_Ethernet26
  shutdown: false
  type: port-channel-member
  channel_group:
    id: 1
    mode: active
port_channel_interfaces:
- name: Port-Channel1
  description: INBAND-MGMT-PARENTS-IPV6_Po26
  type: switched
  shutdown: false
  mode: trunk
  vlans: '106'
ip_igmp_snooping:
  globally_enabled: true
vlans:
- id: 106
  tenant: system
  name: INBAND_MGMT
vlan_interfaces:
- name: Vlan106
  description: Inband Management
  shutdown: false
  mtu: 1500
  ipv6_enable: true
  ipv6_address: 2a00:106::9/64
  type: inband_mgmt
ipv6_static_routes:
- destination_address_prefix: ::/0
  gateway: 2a00:106::1
